<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Alchemy | 千里之行，始于足下</title>
    
    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no">
    <meta name="apple-mobile-app-capable" content="yes">
    <meta name="apple-mobile-app-status-bar-style" content="black">
   
    <meta name="description" content="有关于Alchemy的事">
    <meta name="keywords" content="码农,前端,全栈">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="author" content="cononico">
    <meta name="application-name" content="Cononico" >

    <link rel="stylesheet" type="text/css" href="css/main.css">
    <link rel="stylesheet" type="text/css" href="css/process.css">
    <link rel="shortcut icon"  type="image/x-icon" href="favicon.ico" />
    
    <script type="text/javascript">
        //设定rem值
        document.getElementsByTagName("html")[0].style.fontSize = document.documentElement.clientWidth/20 + 'px';
    </script>
</head>
<body>
	<header class="head">
        <div class="head_logo_div">
            <img class="logo_img" src="https://www.coolecho.net/images/pic/head.jpg"></a>
        </div>
        <div class="head_nav_div">
             <nav class="head_nav">
                <ul id="nav_ul">
                    <li class="nav_li_on nav_ul_li">Home</li>
                    <li class="nav_ul_li">Skill</li>
                    <li class="nav_ul_li">Experience</li>
                    <li class="nav_ul_li">Hobby</li>
                    <li class="nav_ul_li">Contact</li>
                </ul>
            </nav>
        </div>
        <div class="clear"></div>
    </header>
    
    <ul class="float_btn" id="float_btn">
        <li class="btn_on"></li>
        <li></li>
        <li></li>
        <li></li>
    </ul>
    
    <div class="wrapBox" id="wrapBox">
        <div class="box">
            <img class="box_bg" src="images/upload/pic_1.jpg">
            <div class="box01_content">
                <div class="head_div">
                    <div class="cycle_item">
                        <a href="https://github.com/IceEnd" class="github_a" id="github_a" target="_blank">
                            <span class="github_icon"></span>
                            <span class="github_text"><p class="item_name">GitHub</p></span>
                        </a>
                        <a href="http://weibo.com/lavenderecho" class="weibo_a" id="weibo_a" target="_blank">
                            <span class="weibo_icon"></span>
                            <span class="weibo_text"><p class="item_name">微博</p> </span>
                        </a>
                        <a href="http://blog.coolecho.net" class="blog_a" id="blog_a" target="_blank">
                            <span class="blog_icon"></span>
                            <span class="blog_text"><p class="item_name"> 博客</p></span>
                        </a>

                        <div class="green_cycle">
                            <img class="green_cycle_img" src="images/icon/green_cycle.svg">
                            <div class="yellow_cycle">
                                <img class="yellow_cycle_img" src="images/icon/yellow_cycle.svg">
                                <div class="blue_cycle">
                                    <img class="blue_cycle_img" src="images/icon/blue_cycle.svg">
                                    <div class="head_img_div">
                                        <img class="head_img" src="https://www.coolecho.net/images/pic/head.jpg">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <h1 class="title">Cononico</h1>
                <h2 class="title_h2">千里之行，始于足下</h2>
                <div id="box01_text">
                <p class="box01_p">一张画纸一直笔</p>
                <p class="box01_p">一台电脑一杯咖啡</p>
                <p class="box01_p">我仍然可以为这美好的世界献上祝福</p>
                </div>
            </div>
            <div class="arrow_div">
                <img class="arrow_img" src="images/icon/arrowhead.png">
            </div>
        </div>
        
        <div class="box">
            <img class="box_bg" src="images/upload/pic_2.jpg">
            
            <div class="box02_content box_content">
                <div id='bar_container' class="bar_container">
                    <div class='bar mint' data-percent='60' data-skill='码农资质'></div>
                    <div class='bar red' data-percent='85' data-skill='瞎折腾'></div>
                    <div class='bar lila' data-percent='70' data-skill='文学'></div>
                    <div class='bar orange' data-percent='60' data-skill='绘画'></div>
                    <div class='bar gray' data-percent='50' data-skill='五音'></div>
                    <div class="bar blue" data-percent='75' data-skill='同性吸引力'></div>
                    <div class="bar green" data-percent='25' data-skill='异性吸引力'></div>
                </div>
                <div id="box02_text">
                    <h1>About Me</h1>
                    <div class="overline"></div>
                    <p>现居于申城的全职码农</p>
                    <p>喜欢写字、画画、文学</p>
                    <p>已脱宅，爱好游泳、旅游</p>
                    <p>新晋铲屎官</p>                                        
                    <p>常驻B站、GitHub</p>
                </div>
                <div class="clear"></div>
            </div>
            
            <div class="arrow_div">
                <img class="arrow_img" src="images/icon/arrowhead.png">
            </div>
            
        </div>
        
        <div class="box">
            <img class="box_bg" src="images/upload/pic_3.jpg">
            
            <div class="box_content box03_content">
                <ul id="timeUl" class="timeUl">
                     <li>
                       <div>
                            <h1>2017.5-Now</h1>
                            <p>京东商城</p>
                            <p>前端码农</p>
                            <p>对接商城前端业务</p>
                            <p>项目react构建</p>
                        </div>
                    </li>
                    <li>
                        <div>
                            <h1>2016.7-2017.4</h1>
                            <p>诺亚财富</p>
                            <p>前端码农</p>
                            <p>1.玩React，Node.js，UI自动化</p>
                            <p>2.校招毁一生，一生诺亚黑</p>
                        </div>
                    </li>
                    <li>
                        <div>
                            <h1>2015.7-2015.8</h1>
                            <p>武汉万江龙网络有限公司</p>
                            <p>前端&运维 实习生</p>
                            <p>蜗居两个月，往事不堪回首</p>
                        </div>
                    </li>
                    <li>
                        <div>
                            <h1>2012-2016</h1>
                            <p>武汉理工大学</p>
                            <p>专业：计算机科学与技术</p>
                            <p>学院里卧虎藏龙，身边不少大神</p>
                            <p>但从没有佩服过谁<p>
                            <p>因为所有的问题都是我自己解决的</p>
                        </div>
                    </li>
                </ul>
                 <div class="left_div" id="left_div">
                     <img class="left_arrow" src="images/icon/arrowleft.png">
                 </div>
                 <div class="right_div" id="right_div">
                      <img class="right_arrow" src="images/icon/arrowright.png">
                 </div>
            </div>
            
             <div class="arrow_div">
                <img class="arrow_img" src="images/icon/arrowhead.png">
            </div>
        </div>
        
        
        <div class="box">
            
            <img class="box_bg" src="images/upload/pic_4.jpg">
            <div class="box_content box04_content">
                <h1 class="box04_title">Something Of Hobby</h1>
                <ul class="hobby_content">
                    <li class="hobby_01">
                        <div class="hobby_img_div">
                            <div class="spinner spinner_01"></div>
                            <div class="hobby_img">
                                <img src="images/upload/kapok.jpg">
                            </div>
                            <div class="hobby_img_info">
                                <h1>绘画</h1>
                                <h2>手绘&CG</h2>
                            </div>
                        </div>
                        <div class="hobby_text_div">
                            <div class="hobby_img_info_mob">
                                <h1>绘画/<a>手绘&CG</a></h1>
                            </div>
                            <p class="about_p">
                                一切都是兴趣使然，这是一个保持了十几年的爱好，绘画能让我浮躁的心脏完全静下来。从手绘到CG都摸过，不过还是个手残。
                            </p>
                            <p>
                                嗯，我还是有点色弱，配色有难度。
                            </p>
                        </div>
                    </li>
                    <li class="hobby_02">
                        <div class="hobby_img_div">
                            <div class="spinner spinner_02"></div>
                            <div class="hobby_img">
                                <img src="images/upload/acg.png">
                            </div>
                            <div class="hobby_img_info">
                                <h1>编程</h1>
                                <h2>设计&开源</h2>
                            </div>
                        </div>
                        <div class="hobby_text_div">
                            <div class="hobby_img_info_mob">
                                <h1>编程/<a>设计&开源</a></h1>
                            </div>
                            <p class="about_p">
                                花了很多时间在这上面，主要是因为我靠这个吃饭，还想在GitHub上当一个包达人。
                            </p>
                            <p>
                                我不是极客，单纯只是享受解决难题收获结果的快感！
                            </p>
                        </div>
                    </li>
                    <li class="hobby_03">
                        <div class="hobby_img_div">
                            <div class="spinner spinner_03"></div>
                            <div class="hobby_img">
                                <img src="images/upload/reading.jpg">
                            </div>
                            <div class="hobby_img_info">
                                <h1>文字</h1>
                                <h2>读书&写作</h2>
                            </div>
                        </div>
                        <div class="hobby_text_div">
                            <div class="hobby_img_info_mob">
                                <h1>文学/<a>读书&写作</a></h1>
                            </div>
                            <p class="about_p">
                                枕边都会放一本书，喜欢纸墨的触感和味道，喜欢历史散文小说。成为一个作家是从小的梦想。
                            </p>
                            <p>
                                我以后大概也是个靠文字吃饭的人了。
                            </p>
                        </div>
                    </li>
                    <div class="clear"></div>
                </ul>
            </div>
             <div class="arrow_div">
                <img class="arrow_img" src="images/icon/arrowhead.png">
            </div>
        </div>
        
        <foot id="foot" class="foot">
            <h1 class="foot_title">Contact With Me</h1>
            <div class="foot_info_main">
                <ul>
                    <li class="github_items">
                        <a href="https://github.com/IceEnd" target="_blank">GitHub</a>
                    </li>
                    <li class="google_items">
                        <a href="https://www.pixiv.net/member.php?id=19934405" target="_blank">Pixiv</a>
                    
                    </li>
                    <li class="twitter_items">
                        <a href="https://github.com/IceEnd" target="_blank">Twitter</a>
                    
                    </li>
                    <li class="facebook_items">
                        <a href="https://github.com/IceEnd" target="_blank">FaceBook</a>
                    
                    </li>
                    <li class="weibo_items">
                        <a href="http://weibo.com/lavenderecho" target="_blank">微博</a>
                    
                    </li>
                    <li class="zhihu_items">
                        <a href="https://www.zhihu.com/people/Cononico" target="_blank">知乎</a>
                    
                     </li>
                     <li class="blog_items">
                        <a href="https://www.coolecho.net" target="_blank">博客</a>
                    
                     </li>
                     <li class="email_items">
                        <a href="mailto:min@coolecho.net" target="_blank">邮箱</a>
                    </li>
                    <div class="clear"></div>
                </ul>
                <div class="qrcode_div">
                    <span class="weixin">
                        <a class="weixin_icon"></a>
                        <img class="weixin_img" src="images/upload/weixin_qr.png">
                    </span>
                    <span class="dingding">
                        <a class="dingding_icon"></a>
                        <img class="dingding_img" src="images/upload/dingding_qr.png">
                    </span>
                    <span class="qq">
                        <a class="qq_icon"></a>
                        <img class="qq_img" src="images/upload/qq_qr.jpg">
                    </span>
                </div>
            </div>
            <div class="foot_power">
                <h3>©2016-2017 Powerd 
                    <a href="http://weibo.com/lavenderecho" title="Alchemy" target="_blank"> Alchemy's</a>
                    <a href="https://www.coolecho.net" title="IceEnd">绘枫和畅</a>
                    <a href="http://www.miitbeian.gov.cn/" title="beian" target="_blank">鄂ICP备14020745号</a>
                </h3>
            </div>
        </foot>
    </div>
    <script type="text/javascript" src="js/main.js"></script>
</body>
    
</html>
 
